### ISSUE TITLE
Review  #1

### ISSUE THREAD

**Issue by FacundoEG** [LoreBurgi/RSPGame#1]
Hola Lorenzo! para empezar te felicito por haber terminado el desafío del modulo 5!

Lo estuve probando un rato y en líneas generales no le veo ningún error ni nada raro, lo que si me gustaría comentarte, que a la hora de mostrar la jugada, me da la sensación que cambia de escena muy rápido y no se logra ver bien lo que sucede, además que al estar cada jugada en una esquina diferente, hace que quizás sea un poco mas difícil para el usuario saber que paso.

Sacando ese detalle no vi nada mas, igual de todas formas es algo muy chiquito desde el punto de vista del user.

Así que para mi LGTM! te vuelvo a felicitar!
Abrazo!

PD: recorda la próxima cuando envíes el desafío, de mandar el link del repositorio, ya que al enviar solo el link del juego se hace mas complicado encontrar el repo para dejar la review.

**Comment by FacundoEG** [comment]
PD: fijate que en el desafío decía que mandes el link del repositorio, ya que si no es medio complicado agregar un comentario a la review jaja

**Comment by LoreBurgi** [comment]
> Hola Lorenzo! para empezar te felicito por haber terminado el desafío del modulo 5!
> 
> Lo estuve probando un rato y en líneas generales no le veo ningún error ni nada raro, lo que si me gustaría comentarte, que a la hora de mostrar la jugada, me da la sensación que cambia de escena muy rápido y no se logra ver bien lo que sucede, además que al estar cada jugada en una esquina diferente, hace que quizás sea un poco mas difícil para el usuario saber que paso.
> 
> Sacando ese detalle no vi nada mas, igual de todas formas es algo muy chiquito desde el punto de vista del user.
> 
> Así que para mi LGTM! te vuelvo a felicitar!
> Abrazo!
> 
> PD: recorda la próxima cuando envíes el desafío, de mandar el link del repositorio, ya que al enviar solo el link del juego se hace mas complicado encontrar el repo para dejar la review.

Tenes razón recién me doy cuenta que mande el juego y no el repo jajaja q cabeza
